# Generated by Django 5.2.4 on 2025-07-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Одобрен"),
                            ("rejected", "Отклонён"),
                            ("no_answer", "Не взял трубку"),
                            ("not_set", "Не задан"),
                        ],
                        default="not_set",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("telegram", "Telegram"),
                            ("vk", "ВКонтакте"),
                            ("website", "Форма на сайте"),
                            ("schedule", "Смена"),
                            ("camp", "Лагерь"),
                        ],
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "added_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата добавления"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "parent_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя родителя"
                    ),
                ),
                (
                    "interest",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Интерес"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "callback_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время перезвона"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лид",
                "verbose_name_plural": "Лиды",
            },
        ),
    ]
