# Generated by Django 5.2.4 on 2025-07-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "parent_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя родителя"
                    ),
                ),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("camp", "Лагерь"),
                            ("lab", "Лаборатория"),
                            ("full_day", "Полный день"),
                        ],
                        max_length=20,
                        verbose_name="Тип посещения",
                    ),
                ),
                (
                    "default_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Цена по умолчанию",
                    ),
                ),
                (
                    "individual_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Индивидуальная цена",
                    ),
                ),
                (
                    "price_comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий к цене"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schedule.schedule",
                        verbose_name="Смена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученики",
            },
        ),
    ]
