# Generated by Django 5.2.4 on 2025-08-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0002_student_attendance_dates_alter_student_price_comment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="excused",
            field=models.BooleanField(
                default=False, verbose_name="По уважительной причине"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="present",
            field=models.BooleanField(default=False, verbose_name="Присутствовал"),
        ),
    ]
