# Generated by Django 5.2.4 on 2025-08-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_attendance_excused_alter_attendance_present"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="default_price",
            field=models.DecimalField(
                decimal_places=2,
                default=15000,
                max_digits=10,
                verbose_name="Базовая цена",
            ),
        ),
    ]
