# Generated by Django 5.2.4 on 2025-08-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_default_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="comment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="default_price",
            field=models.DecimalField(
                decimal_places=2,
                default=11400,
                max_digits=10,
                verbose_name="Базовая цена",
            ),
        ),
    ]
