# Generated by Django 5.2.4 on 2025-08-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Пополнение"),
                    ("payment", "Списание"),
                    ("refund", "Возврат"),
                ],
                max_length=20,
                verbose_name="Тип операции",
            ),
        ),
    ]
