# Generated by Django 5.2.4 on 2026-01-29 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_position_alter_employee_position'),
        ('schedule', '0001_initial'),
        ('students', '0007_alter_balance_operation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отряда')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squads_led', to='employees.employee', verbose_name='Вожатый/Преподаватель')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='schedule.schedule', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Отряд',
                'verbose_name_plural': 'Отряды',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.squad', verbose_name='Отряд'),
        ),
    ]
