# Generated by Django 5.2.4 on 2026-02-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('students', '0008_squad_student_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='name',
            field=models.IntegerField(verbose_name='Номер отряда'),
        ),
        migrations.AlterUniqueTogether(
            name='squad',
            unique_together={('name', 'schedule')},
        ),
    ]
