# Generated by Django 5.2.4 on 2026-03-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_squad_name_alter_squad_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='special_notes',
            field=models.TextField(blank=True, verbose_name='Особые отметки'),
        ),
    ]
