# Generated by Django 5.2.4 on 2025-07-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeattendance",
            name="present",
            field=models.BooleanField(default=True, verbose_name="Присутствовал"),
        ),
    ]
