# Generated by Django 5.2.4 on 2025-08-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employeeattendance_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeattendance",
            name="excused",
            field=models.BooleanField(
                default=False, verbose_name="По уважительной причине"
            ),
        ),
        migrations.AlterField(
            model_name="employeeattendance",
            name="present",
            field=models.BooleanField(default=False, verbose_name="Присутствовал"),
        ),
        migrations.AlterUniqueTogether(
            name="employeeattendance",
            unique_together={("employee", "date")},
        ),
    ]
