# Generated by Django 5.2.4 on 2025-08-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employeeattendance_excused_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeattendance",
            options={"verbose_name": "Посещение", "verbose_name_plural": "Посещения"},
        ),
        migrations.RemoveField(
            model_name="employeeattendance",
            name="comment",
        ),
        migrations.AlterField(
            model_name="employeeattendance",
            name="present",
            field=models.BooleanField(default=True, verbose_name="Присутствовал"),
        ),
    ]
