# Generated by Django 5.2.4 on 2025-10-27 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0004_city_branch_city"),
        ("employees", "0004_alter_employeeattendance_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="branches.city",
                verbose_name="Город",
            ),
        ),
    ]
