# Generated by Django 5.2.4 on 2025-10-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_alter_employee_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("teacher", "Преподаватель"),
                    ("admin", "Администратор"),
                    ("camp_head", "Начальник лагеря"),
                    ("lab_head", "Начальник лаборатории"),
                ],
                max_length=50,
                verbose_name="Должность",
            ),
        ),
    ]
