# Generated by Django 5.2.4 on 2026-01-30 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_position_alter_employee_position'),
        ('students', '0008_squad_student_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='Является лидером отряда'),
        ),
        migrations.AddField(
            model_name='employee',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='students.squad', verbose_name='Отряд'),
        ),
    ]
