# Generated by Django 5.2.4 on 2026-04-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_is_leader_employee_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='Является вожатым'),
        ),
    ]
