# Generated by Django 5.2.4 on 2025-07-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="schedules",
            field=models.ManyToManyField(
                blank=True, to="schedule.schedule", verbose_name="Закрепленные смены"
            ),
        ),
    ]
