# Generated by Django 5.2.4 on 2025-10-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="priority",
        ),
    ]
