# Generated by Django 5.2.4 on 2025-10-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_ticketmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="conversation",
            field=models.JSONField(blank=True, default=list, verbose_name="Диалог"),
        ),
    ]
