# Generated by Django 5.2.4 on 2025-10-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_ticket_conversation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="conversation",
        ),
        migrations.DeleteModel(
            name="TicketMessage",
        ),
    ]
