# Generated by Django 5.2.4 on 2025-11-02 19:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_ticket_conversation_delete_ticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_screenshot_upload_path, verbose_name='Скриншот'),
        ),
    ]
