# Generated by Django 5.2.4 on 2025-11-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ticket_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='has_unread_admin_response',
            field=models.BooleanField(default=False, verbose_name='Есть непросмотренный ответ администратора'),
        ),
    ]
