# Generated by Django 5.2.4 on 2025-08-04 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("employees", "0002_employeeattendance_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="administrator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_branches",
                to="employees.employee",
                verbose_name="Администратор",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="director_branches",
                to="employees.employee",
                verbose_name="Директор",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Телефон"
            ),
        ),
    ]
