# Generated by Django 5.2.4 on 2025-08-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_branch_administrator_branch_director_branch_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="administrator",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="director",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="email",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="phone",
        ),
    ]
