# Generated by Django 5.2.4 on 2025-07-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название смены"),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "theme",
                    models.CharField(max_length=255, verbose_name="Тематика смены"),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#ff6b6b", "Красный"),
                            ("#51cf66", "Зеленый"),
                            ("#339af0", "Синий"),
                            ("#ffd43b", "Желтый"),
                            ("#cc5de8", "Фиолетовый"),
                            ("#ff922b", "Оранжевый"),
                            ("#20c997", "Бирюзовый"),
                        ],
                        default="#cce6ff",
                        max_length=7,
                        verbose_name="Цвет маркировки",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="branches.branch",
                        verbose_name="Филиал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смена",
                "verbose_name_plural": "Смены",
            },
        ),
    ]
