# Generated by Django 5.2.4 on 2025-07-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Regulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название документа"),
                ),
                (
                    "file",
                    models.FileField(upload_to="regulations/", verbose_name="Файл"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Регламент",
                "verbose_name_plural": "Регламенты",
            },
        ),
    ]
