# Generated by Django 5.2.4 on 2025-07-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Питание"),
                            ("materials", "Материалы"),
                            ("transport", "Транспорт"),
                            ("rent", "Аренда"),
                            ("other", "Прочее"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="schedule.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Фиксированная ставка"),
                            ("percent", "Процент от оплаты"),
                            ("combined", "Фикс + процент"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="Тип выплаты",
                    ),
                ),
                (
                    "days_worked",
                    models.IntegerField(
                        default=0, verbose_name="Количество отработанных дней"
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ставка за день",
                    ),
                ),
                (
                    "percent_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Процент от оплаты",
                    ),
                ),
                (
                    "total_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Итоговая сумма выплаты",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Выплачено"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.schedule",
                        verbose_name="Смена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зарплата сотрудника",
                "verbose_name_plural": "Зарплаты сотрудников",
            },
        ),
    ]
