# Generated by Django 5.2.4 on 2025-08-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_remove_days_worked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="daily_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=10,
                verbose_name="Ставка за день",
            ),
        ),
    ]
